services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - api-gateway
    networks:
      - singapore-health-network

  api-gateway:
    build: 
      context: ./client/src/services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - risk-service
    networks:
      - singapore-health-network

  risk-service:
    build: 
      context: ./client/src/services/risk-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - singapore-health-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=singapore_health
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - singapore-health-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - singapore-health-network

volumes:
  postgres_data:
  redis_data:

networks:
  singapore-health-network:
    driver: bridge